# Generated by Django 4.1.1 on 2022-09-18 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bankCredentials', '0003_bankauth'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=50)),
                ('service_description', models.CharField(max_length=500)),
                ('tag_is_loan', models.BooleanField(default=False)),
                ('tag_is_savings_account', models.BooleanField(default=False)),
                ('origin_link', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceBenefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=500)),
                ('parent_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bankCredentials.bankservice')),
            ],
        ),
    ]
