# Generated by Django 4.0.6 on 2022-09-15 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisor', '0002_savingplan_plan_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savingplan',
            name='allowed_withdraw_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='savingplan',
            name='next_action_date',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
