# Generated by Django 4.0.6 on 2022-09-17 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisor', '0006_savingplan_plan_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='savingplan',
            old_name='is_current',
            new_name='is_active',
        ),
        migrations.RemoveField(
            model_name='savingplan',
            name='initial_amount',
        ),
        migrations.RemoveField(
            model_name='savingplan',
            name='is_frequency_allowed',
        ),
        migrations.RemoveField(
            model_name='savingplan',
            name='next_action_date',
        ),
        migrations.RemoveField(
            model_name='stream',
            name='frequency',
        ),
        migrations.AddField(
            model_name='stream',
            name='tag',
            field=models.CharField(default='000000000000', max_length=50),
        ),
    ]
