# Generated by Django 4.0.6 on 2022-09-18 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisor', '0009_alter_savingplan_allowed_withdraw_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='savingplan',
            name='next_deposit_on',
            field=models.DateField(auto_now=True),
        ),
    ]
