# Generated by Django 4.0.6 on 2022-08-25 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountHolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_first_name', models.CharField(max_length=45)),
                ('user_last_name', models.CharField(max_length=45)),
                ('mobile_number', models.CharField(max_length=14, verbose_name='Phone number')),
            ],
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.BigIntegerField(verbose_name='account number')),
                ('pass_code', models.SmallIntegerField(verbose_name='Pass code')),
                ('current_balance', models.FloatField(default=0)),
                ('account_holder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bankCredentials.accountholder')),
            ],
        ),
        migrations.CreateModel(
            name='SavingAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_amount', models.FloatField(default=0)),
                ('current_amount', models.FloatField(default=0)),
                ('interest_rates', models.FloatField(default=1.2)),
                ('time_interval', models.IntegerField(verbose_name='Saving time frame')),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bankCredentials.bankaccount')),
            ],
        ),
        migrations.CreateModel(
            name='FixedDepositDetail',
            fields=[
                ('savingaccount_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bankCredentials.savingaccount')),
            ],
            bases=('bankCredentials.savingaccount',),
        ),
        migrations.CreateModel(
            name='SavingsDetail',
            fields=[
                ('savingaccount_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bankCredentials.savingaccount')),
            ],
            bases=('bankCredentials.savingaccount',),
        ),
    ]
