# Generated by Django 4.1.1 on 2022-09-18 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bankCredentials', '0005_bankservice_tag_is_insurance'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRequirements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('string_list', models.CharField(max_length=1000)),
                ('minimum', models.IntegerField(default=0)),
                ('maximum', models.IntegerField(default=0)),
                ('duration', models.IntegerField(default=0)),
                ('parent_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bankCredentials.bankservice')),
            ],
        ),
    ]
