# Generated by Django 4.0.6 on 2022-09-15 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisor', '0003_alter_savingplan_allowed_withdraw_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savingplan',
            name='next_action_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
