# Generated by Django 4.0.6 on 2022-09-15 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisor', '0004_alter_savingplan_next_action_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savingplan',
            name='plan_name',
        ),
        migrations.AlterField(
            model_name='savingplan',
            name='allowed_withdraw_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='savingplan',
            name='next_action_date',
            field=models.DateField(null=True),
        ),
    ]
